2019-03-11 20:26:33,527 : INFO : Machine : Mission Pinball Framework Core Engine v0.50.12
2019-03-11 20:26:33,528 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\wilder\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'logfile': 'logs\\2019-03-11-20-26-33-mpf-RedTunic.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None}
2019-03-11 20:26:33,528 : INFO : Machine : MPF path: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-03-11 20:26:33,528 : INFO : Machine : Machine path: C:\Users\Wilder\zelda\monitor
2019-03-11 20:26:33,528 : INFO : Machine : Platform: win32
2019-03-11 20:26:33,529 : INFO : Machine : Python executable location: c:\users\wilder\appdata\local\programs\python\python36\python.exe
2019-03-11 20:26:33,529 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-03-11 20:26:34,196 : INFO : Machine : Machine config file #1: config.yaml
2019-03-11 20:26:34,198 : WARNING : ConfigProcessor : Cache file not found: C:\Users\Wilder\AppData\Local\Temp\91d056545e250861ff20c89c789a3afd.mpf_cache
2019-03-11 20:26:34,198 : INFO : ConfigProcessor : Loading config from file c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml.
2019-03-11 20:26:34,338 : INFO : ConfigProcessor : Loading config: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-03-11 20:26:34,340 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\monitor\config\config.yaml.
2019-03-11 20:26:34,454 : ERROR : root : Could not find file C:\Users\Wilder\zelda\monitor\config\config.yaml
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 135, in load
    file = FileManager.locate_file(filename)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 108, in locate_file
    raise FileNotFoundError("File not found: {}".format(filename))
FileNotFoundError: File not found: C:\Users\Wilder\zelda\monitor\config\config.yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\commands\game.py", line 208, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 158, in __init__
    self._load_config()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 427, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 111, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 131, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 138, in load
    raise IOError("Could not find file {}".format(filename))
OSError: Could not find file C:\Users\Wilder\zelda\monitor\config\config.yaml
