2019-04-30 13:35:07,764 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.0-dev.16
2019-04-30 13:35:07,764 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['x'], 'mpfconfigfile': 'c:\\users\\wilder\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2019-04-30-13-35-07-mpf-RedTunic.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 10, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-04-30 13:35:07,765 : INFO : Machine : MPF path: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-04-30 13:35:07,765 : INFO : Machine : Machine path: C:\Users\Wilder\zelda
2019-04-30 13:35:07,765 : INFO : Machine : Platform: win32
2019-04-30 13:35:07,765 : INFO : Machine : Python executable location: c:\users\wilder\appdata\local\programs\python\python36\python.exe
2019-04-30 13:35:07,765 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-04-30 13:35:07,765 : INFO : Machine : Machine config file #1: x
2019-04-30 13:35:07,767 : WARNING : ConfigProcessor : Cache file not found: C:\Users\Wilder\AppData\Local\Temp\10e83e49692a567799c0a93a40e4efa1.mpf_cache
2019-04-30 13:35:07,767 : INFO : ConfigProcessor : Loading config from file c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml.
2019-04-30 13:35:07,767 : DEBUG : YAML File Interface : Loading file: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-04-30 13:35:07,928 : INFO : ConfigProcessor : Loading config: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-04-30 13:35:07,944 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\config\x.
2019-04-30 13:35:08,046 : ERROR : root : Could not find file C:\Users\Wilder\zelda\config\x
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 80, in load
    file = FileManager.locate_file(filename)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 53, in locate_file
    raise FileNotFoundError("File not found: {}".format(filename))
FileNotFoundError: File not found: C:\Users\Wilder\zelda\config\x

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\commands\game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 180, in __init__
    self._load_config()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 449, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 83, in load
    raise IOError("Could not find file {}".format(filename))
OSError: Could not find file C:\Users\Wilder\zelda\config\x
