2019-05-01 18:02:54,163 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.0-dev.16
2019-05-01 18:02:54,164 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\wilder\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2019-05-01-18-02-54-mpf-RedTunic.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 10, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-05-01 18:02:54,164 : INFO : Machine : MPF path: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-05-01 18:02:54,164 : INFO : Machine : Machine path: C:\Users\Wilder\zelda
2019-05-01 18:02:54,164 : INFO : Machine : Platform: win32
2019-05-01 18:02:54,164 : INFO : Machine : Python executable location: c:\users\wilder\appdata\local\programs\python\python36\python.exe
2019-05-01 18:02:54,164 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-05-01 18:02:54,164 : INFO : Machine : Machine config file #1: config.yaml
2019-05-01 18:02:54,166 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\9bf880992bc5b85aa1bd2cc37b214e56.mpf_cache
2019-05-01 18:02:54,169 : DEBUG : asyncio : Using selector: SelectSelector
2019-05-01 18:02:54,170 : INFO : Machine : Initialise MPF.
2019-05-01 18:02:54,215 : DEBUG : FAST : Configuring FAST hardware.
2019-05-01 18:02:54,415 : INFO : FAST : Connecting to \\.\COM11 at 921600bps
2019-05-01 18:02:54,448 : INFO : FAST : Connected! Processor: NET, Board Type: FP-CPU-002-2, Firmware: 01.02
2019-05-01 18:02:54,449 : INFO : EventManager : Event: ======'machine_var_fast_net_firmware'====== Args={'value': '01.02', 'prev_value': None, 'change': True}
2019-05-01 18:02:54,449 : INFO : EventManager : Event: ======'machine_var_fast_net_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2019-05-01 18:02:54,449 : WARNING : FAST : Not resetting FAST NET because firmware is currently broken.
2019-05-01 18:02:54,512 : INFO : FAST : Connecting to \\.\COM12 at 921600bps
2019-05-01 18:02:54,544 : INFO : FAST : Connected! Processor: RGB, Board Type: FP-CPU-002-2, Firmware: 01.00
2019-05-01 18:02:54,545 : INFO : EventManager : Event: ======'machine_var_fast_rgb_firmware'====== Args={'value': '01.00', 'prev_value': None, 'change': True}
2019-05-01 18:02:54,545 : INFO : EventManager : Event: ======'machine_var_fast_rgb_model'====== Args={'value': 'FP-CPU-002-2', 'prev_value': None, 'change': True}
2019-05-01 18:02:54,545 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2019-05-01 18:02:54,611 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\data/machine_vars.yaml
2019-05-01 18:02:54,614 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 481, 'prev_value': None, 'change': True}
2019-05-01 18:02:54,615 : INFO : EventManager : Event: ======'machine_var_player2_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2019-05-01 18:02:54,615 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.0-dev.16', 'prev_value': None, 'change': True}
2019-05-01 18:02:54,615 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.0-dev.16, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2019-05-01 18:02:54,615 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2019-05-01 18:02:54,615 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-7-6.1.7601-SP1', 'prev_value': None, 'change': True}
2019-05-01 18:02:54,615 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2019-05-01 18:02:54,616 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '7', 'prev_value': None, 'change': True}
2019-05-01 18:02:54,616 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '6.1.7601', 'prev_value': None, 'change': True}
2019-05-01 18:02:54,616 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2019-05-01 18:02:54,616 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2019-05-01 18:02:54,674 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\072dbb4c30ca18f53440337aa5cd71bd.mpf_cache
2019-05-01 18:02:54,679 : DEBUG : ModeController : Loaded mode light_world
2019-05-01 18:02:54,679 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\3485f9bf4bb8d1d21be6de1438e091ba.mpf_cache
2019-05-01 18:02:54,682 : DEBUG : ModeController : Loaded mode skillshot_ballsave
2019-05-01 18:02:54,683 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\96294a9578657f44941f2a8ec647ae36.mpf_cache
2019-05-01 18:02:54,687 : DEBUG : ModeController : Loaded mode rupee3x_finder
2019-05-01 18:02:54,688 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\da675f6b180b79eecb40cb5eb7f75a18.mpf_cache
2019-05-01 18:02:54,692 : DEBUG : ModeController : Loaded mode bomb_finder
2019-05-01 18:02:54,692 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\dbd150f896646081271b7a77a791f2fa.mpf_cache
2019-05-01 18:02:54,696 : DEBUG : ModeController : Loaded mode slide_tracker
2019-05-01 18:02:54,696 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\86e0d165ea95889c95b56598c3ebe263.mpf_cache
2019-05-01 18:02:54,700 : DEBUG : ModeController : Loaded mode music_player
2019-05-01 18:02:54,700 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\dd39e2de39eb354a1ec99be2f3167765.mpf_cache
2019-05-01 18:02:54,705 : DEBUG : ModeController : Loaded mode heartmeter
2019-05-01 18:02:54,705 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\34c6448537d1c95c89cf73a07c0f99c9.mpf_cache
2019-05-01 18:02:54,711 : DEBUG : ModeController : Loaded mode bottle_filler
2019-05-01 18:02:54,711 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\c35ad2e595070cac0b6f696d6f7f6af6.mpf_cache
2019-05-01 18:02:54,716 : DEBUG : ModeController : Loaded mode ball_save
2019-05-01 18:02:54,716 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\final_hold\config\final_hold.yaml
2019-05-01 18:02:54,716 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\final_hold\config\final_hold.yaml.
2019-05-01 18:02:54,717 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\final_hold\config\final_hold.yaml
2019-05-01 18:02:54,735 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 7\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 7\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96>
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "speed" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\final_hold\\config\\final_hold.yaml", line 51, column 7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\final_hold\config\final_hold.yaml: 'Key "speed" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\final_hold\\config\\final_hold.yaml", line 51, column 7'
2019-05-01 18:02:54,818 : INFO : Machine : Starting the main run loop.
2019-05-01 18:02:54,819 : INFO : Machine : Shutting down...
2019-05-01 18:02:54,819 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2019-05-01 18:02:54,822 : ERROR : FAST : Stop called on serial connection \\.\COM12
2019-05-01 18:02:54,823 : ERROR : FAST : Stop called on serial connection \\.\COM11
2019-05-01 18:02:55,125 : ERROR : root : Error found in file C:\Users\Wilder\zelda\modes\final_hold\config\final_hold.yaml: 'Key "speed" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\final_hold\\config\\final_hold.yaml", line 51, column 7'
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "speed" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\final_hold\\config\\final_hold.yaml", line 51, column 7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\commands\game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 716, in run
    self._run_loop()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 776, in _run_loop
    raise self._exception['exception']
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\final_hold\config\final_hold.yaml: 'Key "speed" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\final_hold\\config\\final_hold.yaml", line 51, column 7'
