2019-05-06 13:16:14,406 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.0-dev.16
2019-05-06 13:16:14,407 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\wilder\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2019-05-06-13-16-14-mpf-RedTunic.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 10, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-05-06 13:16:14,407 : INFO : Machine : MPF path: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-05-06 13:16:14,407 : INFO : Machine : Machine path: C:\Users\Wilder\zelda
2019-05-06 13:16:14,407 : INFO : Machine : Platform: win32
2019-05-06 13:16:14,407 : INFO : Machine : Python executable location: c:\users\wilder\appdata\local\programs\python\python36\python.exe
2019-05-06 13:16:14,407 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-05-06 13:16:14,407 : INFO : Machine : Machine config file #1: config.yaml
2019-05-06 13:16:14,410 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\9bf880992bc5b85aa1bd2cc37b214e56.mpf_cache
2019-05-06 13:16:14,413 : DEBUG : asyncio : Using selector: SelectSelector
2019-05-06 13:16:14,414 : INFO : Machine : Initialise MPF.
2019-05-06 13:16:14,452 : DEBUG : Virtual Platform : Configuring virtual hardware interface.
2019-05-06 13:16:14,656 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2019-05-06 13:16:14,726 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\data/machine_vars.yaml
2019-05-06 13:16:14,729 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 86, 'prev_value': None, 'change': True}
2019-05-06 13:16:14,729 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.53.0-dev.16', 'prev_value': None, 'change': True}
2019-05-06 13:16:14,729 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.53.0-dev.16, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2019-05-06 13:16:14,729 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.6.4', 'prev_value': None, 'change': True}
2019-05-06 13:16:14,729 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-7-6.1.7601-SP1', 'prev_value': None, 'change': True}
2019-05-06 13:16:14,729 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2019-05-06 13:16:14,730 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '7', 'prev_value': None, 'change': True}
2019-05-06 13:16:14,730 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '6.1.7601', 'prev_value': None, 'change': True}
2019-05-06 13:16:14,730 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2019-05-06 13:16:14,730 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2019-05-06 13:16:14,792 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\8b601767b8d464abeaa513b42e6346a8.mpf_cache
2019-05-06 13:16:14,796 : DEBUG : ModeController : Loaded mode master_sword_buildup
2019-05-06 13:16:14,796 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\58664c35241624b07b13025a5964d2a4.mpf_cache
2019-05-06 13:16:14,801 : DEBUG : ModeController : Loaded mode video_player
2019-05-06 13:16:14,801 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\b0bcc174d8c9595c3b107b2ba9cf1c73.mpf_cache
2019-05-06 13:16:14,809 : DEBUG : ModeController : Loaded mode attract_carousel
2019-05-06 13:16:14,809 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\072dbb4c30ca18f53440337aa5cd71bd.mpf_cache
2019-05-06 13:16:14,814 : DEBUG : ModeController : Loaded mode light_world
2019-05-06 13:16:14,814 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\dbd150f896646081271b7a77a791f2fa.mpf_cache
2019-05-06 13:16:14,819 : DEBUG : ModeController : Loaded mode slide_tracker
2019-05-06 13:16:14,819 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\27a949ddf2d3e5eeb9247bd991aba200.mpf_cache
2019-05-06 13:16:14,823 : DEBUG : ModeController : Loaded mode darkworld2
2019-05-06 13:16:14,823 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6fc1a42fdd0d487285862f5b943c745e.mpf_cache
2019-05-06 13:16:14,827 : DEBUG : ModeController : Loaded mode rupee_finder
2019-05-06 13:16:14,827 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\34c6448537d1c95c89cf73a07c0f99c9.mpf_cache
2019-05-06 13:16:14,831 : DEBUG : ModeController : Loaded mode bottle_filler
2019-05-06 13:16:14,831 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\c3fd2c292a6c0d3463ad9b4555730ad5.mpf_cache
2019-05-06 13:16:14,835 : DEBUG : ModeController : Loaded mode item_tracker
2019-05-06 13:16:14,836 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\b0ee6a771658ae3fb7e70c6d5ff59887.mpf_cache
2019-05-06 13:16:14,845 : DEBUG : ModeController : Loaded mode game
2019-05-06 13:16:14,846 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\aecceeb5afbfdc7257044e8417ebcf98.mpf_cache
2019-05-06 13:16:14,853 : DEBUG : ModeController : Loaded mode attract
2019-05-06 13:16:14,853 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\3485f9bf4bb8d1d21be6de1438e091ba.mpf_cache
2019-05-06 13:16:14,857 : DEBUG : ModeController : Loaded mode skillshot_ballsave
2019-05-06 13:16:14,857 : INFO : ConfigProcessor : Loading config from cache: C:\Users\Wilder\AppData\Local\Temp\6cbeeb809d9de6fbbf2951c4e6867473.mpf_cache
2019-05-06 13:16:14,863 : DEBUG : ModeController : Loaded mode darkworld
2019-05-06 13:16:14,863 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\modes\base\config\base.yaml
2019-05-06 13:16:14,863 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\modes\base\config\base.yaml.
2019-05-06 13:16:14,864 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\modes\base\config\base.yaml
2019-05-06 13:16:14,944 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 5\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...column 5\'',)>) at c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py:96>
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "x" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\base\\config\\base.yaml", line 151, column 5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\base\config\base.yaml: 'Key "x" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\base\\config\\base.yaml", line 151, column 5'
2019-05-06 13:16:15,034 : INFO : Machine : Starting the main run loop.
2019-05-06 13:16:15,034 : INFO : Machine : Shutting down...
2019-05-06 13:16:15,034 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2019-05-06 13:16:15,135 : ERROR : root : Error found in file C:\Users\Wilder\zelda\modes\base\config\base.yaml: 'Key "x" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\base\\config\\base.yaml", line 151, column 5'
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 198, in load
    config = self.process(f)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 224, in process
    return yaml.load(data_string, Loader=MpfLoader)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 104, in get_single_data
    return self.construct_document(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 114, in construct_document
    for dummy in generator:
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\constructor.py", line 611, in construct_yaml_map
    value = self.construct_mapping(node)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 135, in construct_mapping
    format(key, key_node.start_mark))
KeyError: 'Key "x" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\base\\config\\base.yaml", line 151, column 5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\commands\game.py", line 220, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 716, in run
    self._run_loop()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 776, in _run_loop
    raise self._exception['exception']
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\events.py", line 99, in _async_handler_done
    future.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 117, in load_modes
    self.machine.modes[mode] = self._load_mode(mode)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 266, in _load_mode
    config = self._load_mode_config(mode_string)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\mode_controller.py", line 184, in _load_mode_config
    store_to_cache=self.machine.options['create_config_cache'])
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 112, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 132, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 99, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 212, in load
    raise ValueError(msg)
ValueError: Error found in file C:\Users\Wilder\zelda\modes\base\config\base.yaml: 'Key "x" was defined multiple times in config   in "C:\\Users\\Wilder\\zelda\\modes\\base\\config\\base.yaml", line 151, column 5'
