2019-04-22 17:25:33,727 : INFO : Machine : Mission Pinball Framework Core Engine v0.53.0-dev.16
2019-04-22 17:25:33,728 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\users\\wilder\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2019-04-22-17-25-33-mpf-RedTunic.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 10, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2019-04-22 17:25:33,729 : INFO : Machine : MPF path: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf
2019-04-22 17:25:33,729 : INFO : Machine : Machine path: C:\Users\Wilder\zelda
2019-04-22 17:25:33,729 : INFO : Machine : Platform: win32
2019-04-22 17:25:33,729 : INFO : Machine : Python executable location: c:\users\wilder\appdata\local\programs\python\python36\python.exe
2019-04-22 17:25:33,729 : INFO : Machine : Python version: 3.6.4 (64-bit)
2019-04-22 17:25:33,730 : INFO : Machine : Machine config file #1: config.yaml
2019-04-22 17:25:33,731 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\Wilder\zelda\config\config.yaml
2019-04-22 17:25:33,732 : INFO : ConfigProcessor : Loading config from file c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml.
2019-04-22 17:25:33,732 : DEBUG : YAML File Interface : Loading file: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-04-22 17:25:33,921 : INFO : ConfigProcessor : Loading config: c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\mpfconfig.yaml
2019-04-22 17:25:33,941 : INFO : ConfigProcessor : Loading config from file C:\Users\Wilder\zelda\config\config.yaml.
2019-04-22 17:25:33,941 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\config.yaml
2019-04-22 17:25:34,018 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\config.yaml
2019-04-22 17:25:34,018 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\hardware.yaml
2019-04-22 17:25:34,272 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\hardware.yaml
2019-04-22 17:25:34,275 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\keyboard.yaml
2019-04-22 17:25:34,302 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\keyboard.yaml
2019-04-22 17:25:34,305 : DEBUG : YAML File Interface : Loading file: C:\Users\Wilder\zelda\config\videos.yaml
2019-04-22 17:25:34,394 : INFO : ConfigProcessor : Loading config: C:\Users\Wilder\zelda\config\videos.yaml
2019-04-22 17:25:34,403 : INFO : ConfigProcessor : Config file cache created: C:\Users\Wilder\AppData\Local\Temp\9bf880992bc5b85aa1bd2cc37b214e56.mpf_cache
2019-04-22 17:25:34,405 : DEBUG : asyncio : Using selector: SelectSelector
2019-04-22 17:25:34,406 : INFO : Machine : Initialise MPF.
2019-04-22 17:25:34,456 : DEBUG : FAST : Configuring FAST hardware.
2019-04-22 17:25:34,644 : INFO : FAST : Connecting to \\.\COM11 at 921600bps
2019-04-22 17:25:34,702 : ERROR : Machine : Failed to initialise MPF
Traceback (most recent call last):
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 703, in initialise_mpf
    raise init.exception()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 217, in initialise
    yield from self.initialise_core_and_hardware()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 212, in initialise_core_and_hardware
    yield from self._initialize_platforms()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\machine.py", line 306, in _initialize_platforms
    result.result()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\platforms\fast\fast.py", line 162, in initialize
    yield from self._connect_to_hardware()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\platforms\fast\fast.py", line 234, in _connect_to_hardware
    yield from comm.connect()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\platforms\base_serial_communicator.py", line 40, in connect
    yield from self._connect_to_hardware(self.port, self.baud, self.xonxoff)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\platforms\base_serial_communicator.py", line 49, in _connect_to_hardware
    self.reader, self.writer = yield from connector
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\mpf\core\clock.py", line 151, in open_serial_connection
    **kwargs)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\asyncio\coroutines.py", line 212, in coro
    res = func(*args, **kw)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\serial_asyncio\__init__.py", line 410, in create_serial_connection
    ser = serial.serial_for_url(*args, **kwargs)
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\serial\__init__.py", line 88, in serial_for_url
    instance.open()
  File "c:\users\wilder\appdata\local\programs\python\python36\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port '\\\\.\\COM11': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2019-04-22 17:25:34,795 : INFO : root : MPF run loop ended.
